version: '2.4'

services:
  netswitch:
    image: beasteers/netswitch:latest
    build: "./"
    privileged: true
    network_mode: host
    #cap_add:
    #  - NET_ADMIN
    volumes:
      - /etc/wpa_supplicant/wpa_supplicant.conf:/etc/wpa_supplicant/wpa_supplicant.conf
      - /etc/wpa_supplicant/aps:/etc/wpa_supplicant/aps
    environment:
      LIFELINE_SSID: s0nycL1f3l1ne
