version: '2.4'

services:
  netswitch:
    image: beasteers/netswitch:latest
    build: "./"
    privileged: true
    network_mode: host
    #cap_add:
    #  - NET_ADMIN
    volumes:
      - /etc/wpa_supplicant:/etc/wpa_supplicant
    environment:
      LIFELINE_SSID: iot-lifeline
